### ISSUE TITLE
Auto Compression issues summary

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/Auto-Compression#28]
Currently, several issues have been posted, but there are many similar issues and they are not organized at a glance.
Therefore, based on the existing issues, the tasks to be processed in the Auto Compression repository in the future have been summarized as one issue.

# Model and task support
- [ ] Various model support (#4)
- [ ] (classification) ImageNet task support (#8)
- [ ] Various IoT task support (e.g., object detection) (#15)

# Compression
- [ ] Hyperparameter auto tuner (#6)
- [ ] Progressive quantization (#7)
- [ ] Model converter for pruned weight (#9)
- [ ] Generalizing hyperparameters for compression (#10)
- [ ] Improve logging method (#11)
- [ ] Sampling from the finally trained model (#12)
- [ ] Selection probability print (#13)
- [ ] Resume capability (#14)

First of all, I will close all related issues.
When necessary, I hope to reopen the issue and work on it.

**Comment by LeeHayun** [comment]
This issue has been inactive for a long time and no longer reflects our current priorities. I'm closing it for now. If you believe this matter should be revisited or if you have new insights, please feel free to open a new issue so we can take a fresh look. Thank you for your contributions.
